spring.application.name=example18_SpringBoot

## Server Configuration
#server.port=8080
#server.servlet.context-path=/myapp

## For Random Server port configuration in spring boot
## using server.port = 0
#server.port=0

## when you see autoconfiguration report by spring boot which contain 4 things + - matches , exclusion and unconditional class
## use debug = true when it is false not 4 things visible
#debug=true

# disable Thymeleaf chahing b/c when change the content it restart the server
# not good in development enviroment but good in production enviroment
#spring.thymeleaf.cache=false

# no need to false chaching b/c dev tool disable all chaching mechism