spring.application.name=example18_SpringBoot

## Server Configuration
server.port=8081
server.servlet.context-path=/eazyschool

## For Random Server port configuration in spring boot
## using server.port = 0
#server.port=0

## when you see autoconfiguration report by spring boot which contain 4 things + - matches , exclusion and unconditional class
## use debug = true when it is false not 4 things visible
#debug=true